[package]
name = "blog_v1"
version = "0.1.0"
edition = "2018"  # TODO: 2021

[dependencies]
bitflags = "2.5.0"
multiboot2 = { version = "0.20.0", default-features = false }
spin = "0.5.2"
volatile = "0.2.6"
x86_64 = "0.15.1"

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]
